### ISSUE TITLE
Problems with special characters

### ISSUE THREAD

**Issue by juanbrujo** [maciejczyzewski/hyhyhy#15]
Command:
$ hyhyhy new

Then filling the basic information, the bash throws an error with encoding special characters (like `ñ` a spanish character):

"error: "\xC3" on US-ASCII. Use --trace to view backtrace"

**Comment by pluma** [comment]
`s/special/non-ASCII/g`

**Comment by maciejczyzewski** [comment]
Try now. Check that it is still a mistake.

https://github.com/maciejczyzewski/hyhyhy/commit/2f6a0601d870dfeb21c9b4e3799df1981049716a

**Comment by juanbrujo** [comment]
Should I reinstall hyhyhy from the gem?

Description passes, not author (My name uses the `ñ`character)

Same for `$ hyyhy build` throws same error: `error: "\xC3" on US-ASCII. Use --trace to view backtrace`

**Comment by maciejczyzewski** [comment]
Yes. Try to reinstall.

**Comment by juanbrujo** [comment]
Sorry @maciejczyzewski , uninstalled and reinstalled gem. Same error.

![hyhyhy](https://cloud.githubusercontent.com/assets/362186/5763640/eac27760-9cca-11e4-8865-422d70ce417a.png)

**Comment by maciejczyzewski** [comment]
Finally, now it should work! Check, pls.

**Comment by juanbrujo** [comment]
Awesome @maciejczyzewski , now building perfectly. Closing issue, thanks a lot. Let's try hyhyhy in deep.
